### ISSUE TITLE
Draw options?

### ISSUE THREAD

**Issue by luigifab** [raalkml/gpx2tiles#1]
Is there some options (command line or in gpx files) to customize the lines?
For example the line width and the line color?

**Comment by raalkml** [comment]
Line width (thickness) can be configured for each zoom level: -t <level>:<pixel-width>[+]. E.g. -t 1:3 sets the thickness for the zoom level 1 to 3 pixels. If the last character is "+", the thickness is set for all zoom levels above the stated.

I never implemented changing of the line color, sorry. It isn't hard (look for spdclr array in gpx2tiles.c), just never came to actually do it.

**Comment by luigifab** [comment]
Thank you, that's what I want.

**Comment by raalkml** [comment]
FWIW, I added an option to set the track color (-c <color>, eg. -c ff0000 to draw a very red track).

**Comment by luigifab** [comment]
That's perfect!
